RSI/Controllers/RDController.cs
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.SS.Util;
using NPOI.XSSF.UserModel;
using NPOI.HSSF.Util;
using NPOI.XSSF.Util;
using NPOI.OpenXmlFormats.Spreadsheet;
using RSI.Models.Entity;
using RSI.Models.Manager;
using RSI.Models.Utility;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RSI.Controllers
{
    [SessionState(System.Web.SessionState.SessionStateBehavior.Disabled)]
    public class RDController : Controller
    {
        [Auto_Identify]
        public ActionResult RDReview()
        {
            var rsi_no = Validate.DecryptValue(Request.QueryString["rsi_no"]);
            var part_type = Validate.DecryptValue(Request.QueryString["part_type"]);
            H_Product_InfoEntity h_Product_Info = H_Product_InfoManager.GetH_Product_InfoEntities(rsi_no, part_type).FirstOrDefault();
            return View(h_Product_Info);
        }

        [HttpPost]
        public ActionResult RDReview_NormalParts(string rsi_no, string part_type)
        {
            return Json(H_Product_DetailManager.GetRDReviewNormalParts(rsi_no, part_type));
        }

        [HttpPost]
        public ActionResult RDReview_SpecialParts(string rsi_no, string group_id)
        {
            var model = H_Product_DetailManager.GetRDReviewSpecialParts(rsi_no);
            if (model.Any() && !String.IsNullOrEmpty(group_id))
                model = model.Where(p => p.GROUP_ID == group_id).ToList();
            return Json(model);
        }

        [HttpPost]
        public ActionResult SaveForLayer1(H_Product_DetailEntity h_Product_Details, string rsi_no)
        {
            try
            {
                if (h_Product_Details != null)
                {
                    H_Product_DetailManager.Update_Product_Detail_For_Layer1(h_Product_Details);
                }
                return Json(true);

            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }

        [HttpPost]
        public ActionResult SubmitForLayer1(string rsi_no, string part_type, string bu, string projectname, string phase_id)
        {
            try
            {
                H_Product_DetailManager.Update_Product_Detail_For_Layer1_Submit(rsi_no, part_type);
                H_Product_DetailManager.InsertLogForReturnSubmit(rsi_no, part_type, Employee.EmpNO);

                var dt_SigningNotice = RSI_ConfigEntityDAL.GetSigningNotice(bu, "RESEND", phase_id);
                if (dt_SigningNotice.Rows.Count != 0)
                {
                    var sendMailCode = ConfigurationManager.AppSettings["SendMailCode"].ToString();
                    var attr2 = dt_SigningNotice.Rows[0]["ATTRIBUTE2"].ToString(); //是否啟用(Y/N)
                    var attr4 = dt_SigningNotice.Rows[0]["ATTRIBUTE4"].ToString(); //mailcc是否啟用(Y/N)
                    var attr5 = dt_SigningNotice.Rows[0]["ATTRIBUTE5"].ToString(); //mailcc的boss_level
                    var dt_mailto = RSI_ConfigEntityDAL.GetMailToApprover(rsi_no, part_type);
                    var dt_mailcc = RSI_ConfigEntityDAL.GetMailCCApprover(rsi_no, part_type);
                    var mail = string.Empty;
                    var ccmail = string.Empty;

                    if (attr2.Equals("Y"))
                    {
                        using (IDS.MailSoapClient ids = new IDS.MailSoapClient())
                        {
                            var title = "【RSI】RD重新送出通知: {0}";
                            title = string.Format(title, string.Concat(bu, "-", projectname, "-", part_type));
                            #region mail Body Content
                            var body = string.Empty;
                            body += @"<html>
                                        <body>
                                            <p>Dears,</p>
                                            <p>
                                                RSI表單已由RD修正後重新送出,需要您簽核. <br/>
                                                表單資訊:<br/>
                                                BU:{1}<br/>
                                                BU RFQ No:{2}<br/>
                                                PART TYPE:{3}<br/>
                                                請進入RSI系統查詢相關訊息。謝謝！<br/>
                                                系統超連結:<a href='{0}/RSI'>RSI</a>
                                                RSI表單需要您簽核.<br/>
                                            </p>
                                            <p>簽核資訊</p>
                                            {tableContent}
                                        </body>
                                       </html>";
                            body = body.Replace("{0}", "http://" + Request.Url.Host).Replace("{1}", bu).Replace("{2}", projectname).Replace("{3}", part_type);
                            #endregion
                            #region table Content 簽核資訊
                            var tableData = DASHBOARD_LIST_VManager.GetDetailApprove(rsi_no, part_type);
                            var tableContent = @"<table style='width:100%;'>
                                        <thead>
                                            <tr style='background-color: #3c8dbc !important; color: #fff !important;'>
                                                <th>SEQ</th>
                                                <th>Process Name</th>
                                                <th>Approver</th>
                                                <th>Actual Approver</th>
                                                <th>Status</th>
                                                <th>Comment</th>
                                                <th>Begin Date</th>
                                                <th>End Date</th>
                                                <th>Working Days</th>
                                            </tr>
                                        </thead>
                                        <tbody>{0}</tbody>
                                     </table>";
                            var tbodyContent = string.Empty;
                            var tbodyTemplate = @"<tr>
                                        <td>{0}</td>
                                        <td>{1}</td>
                                        <td>{2}</td>
                                        <td>{3}</td>
                                        <td>{4}</td>
                                        <td>{5}</td>
                                        <td>{6}</td>
                                        <td>{7}</td>
                                        <td style='text-align: right;'>{8}</td>
                                      </tr>";
                            foreach (var item in tableData)
                            {
                                tbodyContent += string.Format(tbodyTemplate, item.APP_SERIAL, item.PHASE,
                                                              item.APP_ASSIGNER_NAME ?? "", item.APP_ACTOR_NAME ?? "",
                                                              item.STATUS, item.APP_CONTENT ?? "",
                                                              item.BEGIN_DATE != null ? ((DateTime)item.BEGIN_DATE).ToString("yyyy/MM/dd hh:mm:ss") : "",
                                                              item.END_DATE != null ? ((DateTime)item.END_DATE).ToString("yyyy/MM/dd hh:mm:ss") : "",
                                                              item.DIF_DAY != null ? ((decimal)item.DIF_DAY).ToString() : "");
                            }
                            tableContent = string.Format(tableContent, tbodyContent);
                            body = body.Replace("{tableContent}", tableContent);
                            #endregion

                            var tempMailTo = dt_mailto.AsEnumerable().Select(p => p.Field<string>("MAILTO")).ToList();
                            var tempMailCC = attr4.Equals("Y") ? dt_mailcc.AsEnumerable().Select(p => p.Field<string>("MAILCC")).ToList() : new List<string>();
                            mail = string.Join(";", tempMailTo);
                            ccmail = attr4.Equals("Y") ? string.Join(";", tempMailCC) : "";
                            ids.ManualSend_07(sendMailCode, mail, ccmail, title, body);
                        }
                    }
                }

                return Json(true);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }

        [HttpPost]
        public ActionResult DeleteSpecialPart(string group_id)
        {
            try
            {
                H_Product_DetailManager.UpdateForDeleteSpecialPart(group_id);
                return Json(true);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }

        [Auto_Identify]
        public ActionResult RDBossReview()
        {
            var rsi_no = Validate.DecryptValue(Request.QueryString["rsi_no"]);
            var part_type = Validate.DecryptValue(Request.QueryString["part_type"]);
            H_Product_InfoEntity h_Product_Info = H_Product_InfoManager.GetH_Product_InfoEntities(rsi_no, part_type).FirstOrDefault();
            return View(h_Product_Info);
        }

        [HttpPost]
        public ActionResult RDBossReview_NormalParts(string rsi_no, string part_type)
        {
            return Json(H_Product_DetailManager.GetRDReviewNormalParts(rsi_no, part_type));
        }

        [HttpPost]
        public ActionResult RDBossReview_SpecialParts(string rsi_no, string group_id)
        {
            var model = H_Product_DetailManager.GetRDReviewSpecialParts(rsi_no);
            if (model.Any() && !String.IsNullOrEmpty(group_id))

RSI/Views/RD/PartNoSearch.cshtml
@model IEnumerable<RSI.Models.Entity.Part_InfoEntity>
@{
    ViewBag.Title = "料號快速查詢";
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title</title>

    @*  Sample demo to reference JS&Css with Bundles*@
    @Styles.Render("~/bundles/style")
    @Styles.RenderFormat("<link href='{0}' rel='stylsheet' type='text/css' media='print' />", "~/bundles/style/print")
    <link href="@Url.Content("~/Content/Css/dataTables.bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <style>
        .table > thead > tr > th {
            vertical-align: middle;
            text-align: center;
        }
    </style>
</head>
<body class="sidebar-mini skin-blue-light fixed">
    <section class="content container-fluid">
        <form>

            <div class="row">
                <div class="col-sm-3 form-group">
                    <label>Part No</label>
                    <input type="text" class="form-control" name="item_no">
                </div>
                <div class="col-sm-3 form-group">
                    <label>Part Level</label>
                    <select id="part_level" name="part_level" class="form-control"></select>
                </div>
                <div class="col-sm-3 form-group">
                    <label>English Name</label>
                    <select id="english_name" name="english_name" class="form-control"></select>
                </div>
                <div class="col-sm-3 form-group">
                    <label>Part Description</label>
                    <input type="text" class="form-control" name="item_desc">
                </div>
                <div class="col-sm-3 form-group">
                    <label>Maker PN</label>
                    <input type="text" class="form-control" name="maker_pn">
                </div>
                <div class="col-sm-3 form-group">
                    <label>Maker</label>
                    <input type="text" class="form-control" name="vendor">
                </div>
                <div class="col-sm-3 form-group">
                    <label>Remark</label>
                    <input type="text" class="form-control" name="remark">
                </div>
                <div class="col-sm-3 form-group hidden">
                    <label>Material Parts</label>
                    <input type="text" class="form-control" name="martial_parts" value="@Request.QueryString["martial_parts"]" disabled="disabled">
                </div>
                <div class="col-sm-3 form-group">
                    <label></label>
                    <input type="button" class="btn btn-default" style="margin-top:25px;" value="Query" onclick="return formsubmit()" />
                </div>
            </div>
        </form>

        <table class="table table-bordered table-hover" id="table">
            <thead>
                <tr class="bg-light-blue">
                    <th>Item No</th>
                    <th>English Name</th>
                    <th>Item Desc</th>
                    <th>Maker PN</th>
                    <th>Marker</th>
                    <th>Release</th>
                    <th></th>
                </tr>
            </thead>
        </table>

    </section>

    @{
        string version = RSI.Models.Entity.RSI_ConfigEntityDAL.GetVersion();
    }

    @Scripts.Render("~/bundles/script")
    <script src="@Url.Content("~/Content/Scripts/jquery.dataTables.min.js?" + version)"></script>
    <script src="@Url.Content("~/Content/Scripts/dataTables.bootstrap.min.js?" + version)"></script>
    <script type="text/javascript">
        function SetPartNoInfo(btn) {
            var tr = $(btn).closest("tr");
            var item_no = $(tr).find("td:eq(0)").text();
            var english_name = $(tr).find("td:eq(1)").text();
            var item_desc = $(tr).find("td:eq(2)").text();
            var maker_pn = $(tr).find("td:eq(3)").text();
            var vendor = $(tr).find("td:eq(4)").text();
            var release_date = $(tr).find("td:eq(5)").text();
            var part_level = $('#part_level').val();

            var part_level = $('#part_level').val();
            var english_name = $('#english_name').val();
            $.ajax({
                url: 'PartNoSearch_Material',
                type: 'POST',
                data: {
                    part_level: part_level,
                    english_name: english_name
                },
                success: function (response) {
                    console.log(response);
                    window.opener.SetPartNoInfo(item_no, english_name, item_desc, vendor, maker_pn, release_date, part_level, response.material_group, response.material_parts);
                    window.close();
                }
            });
        }
        var table = $("#table");
        var part_level = '@Request.QueryString["part_level"]';
        var english_name = '@Request.QueryString["english_name"]';
        $(function () {
            $(table).DataTable();
            GetPartLevelArray();

            $('#part_level').val(part_level);
            $('#english_name').val(english_name);
        });

        function formsubmit() {
            var part_level = $("select[name='part_level']").val();
            var english_name = $("select[name='english_name']").val();
            var item_no = $("input[name='item_no']").val();
            var item_desc = $("input[name='item_desc']").val();
            var maker_pn = $("input[name='maker_pn']").val();
            var vendor = $("input[name='vendor']").val();
            var remark = $("input[name='remark']").val();
            if (part_level == '') {
                alert("請選擇料階");
                return false;
            }

            if (english_name == '') {
                alert('請選擇English Name');
                return false;
            }

            //if (item_desc == "" && maker_pn == "" && vendor == "" && remark == "") {
            //    alert("請輸入查詢條件");
            //    return false;
            //}

            $(table).DataTable().destroy();

            $(table).DataTable({
                ajax: {
                    url: '/RSI/RD/PartNoSearch',
                    method: 'POST',
                    data: {
                        part_level: part_level,
                        english_name: english_name,
                        item_no: item_no,
                        item_desc: item_desc,
                        maker_pn: maker_pn,
                        vendor: vendor,
                        remark: remark
                    },
                    dataSrc: ''
                },
                columns: [
                    { data: 'ITEM_NO' },
                    { data: 'ENGLIST_NAME' },
                    { data: 'ITEM_DESC' },
                    { data: 'Maker_PN' },
                    { data: 'VENDOR' },
                    { data: 'RELEASE_DATE' },
                    {
                        render: function (data, type, row) {
                            return "<input class='btn bg-light-blue' type='button' value='帶入' onclick = 'SetPartNoInfo(this);' />";
                        }
                    }
                ]
            });
        }

        function GetPartLevelArray(query) {
            $.ajax({
                url: 'PartNoSearch_PartLevel',
                type: 'POST',
                data: {
                    query: query
                },
                success: function (response) {
                    $('#part_level').empty();
                    $('#part_level').append("<option value=''></option>");
                    $.each(response, function (index, value) {
                        var optionString = '<option value="{0}">{1}</option>'.replace('{0}', value).replace('{1}', value);
                        $('#part_level').append(optionString);
                    });

                    //if (response.length === 1) {
                    //    $('#part_level').val(query);
                    //    GetEnglishName(response[0]);
                    //    GetMaterialParts(response[0]);
                    //}
                }
            });
        }

        function GetEnglishName(query) {
            $.ajax({
                url: 'PartNoSeach_EnglishName',
                type: 'POST',
                data: {
                    part_level: query
                },
                success: function (response) {
                    $('#english_name').empty();
                    var optionString = '<option value=""></option>';
                    $('#english_name').append(optionString);
                    $.each(response, function (index, value) {
                        optionString = '<option value="{0}">{1}</option>'.replace('{0}', value).replace('{1}', value);
                        $('#english_name').append(optionString);
                    });
                }
            });
        }

        //function GetMaterialParts(query) {
        //    $.ajax({
        //        url: 'PartNoSeach_MaterialParts',
        //        type: 'POST',
        //        data: {
        //            part_level: query
        //        },
        //        success: function (response) {
        //            $('input[name="martial_parts"]').val(response);
        //        }
        //    });
        //}

        $(document).on('change', 'input[name="item_no"]', function () {
            var query = $(this).val();
            query = query.substring(0, 2);
            //GetPartLevelArray(query);
            $('select[name="part_level"]').val(query);
            GetEnglishName(query);
        });

        $(document).on('change', 'select[name="part_level"]', function () {
            var query = $(this).val();
            GetEnglishName(query);
            //GetMaterialParts(query);
        });
    </script>
</body>
</html>

RSI/Views/RD/RDBossReview.cshtml
@model RSI.Models.Entity.H_Product_InfoEntity
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = RSI.Models.Entity.Employee.GetSiteName(Request.QueryString["phase_id"], Request.QueryString["BU"]);
}
@section custom_css_reference {
    <link href="@Url.Content("~/Content/Css/dataTables.bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Third-Part/Select-1.2.6/css/select.bootstrap.min.css")" rel="stylesheet" />
}

@section custom_style{
    <style>
        table tbody tr td.whitespacepre {
            white-space: pre !important;
        }

        .text-ellipsis {
            max-width: 120px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }

            .text-ellipsis:hover {
                white-space: normal;
            }

        .fa-minus-circle, fa-plus-circle {
            cursor: pointer;
        }

        table.dataTable tbody > tr.selected td, table.dataTable tbody > tr > .selected {
            background-color: #9e9e9e;
            /*color: #000;*/
        }

            table.dataTable tbody > tr.selected:hover td, table.dataTable tbody > tr > .selected:hover {
                background-color: #9e9e9e;
                /*color: #000;*/
            }

        .text-bold {
            font-weight: bold;
        }
    </style>
}

@Html.Partial("~/Views/RSI/BasicPage.cshtml", Model)

@*<iframe src="@Url.Action("Boss_TableView", "RD", new { rsi_no=Request.QueryString["rsi_no"], part_type=Request.QueryString["part_type"], phase_id=Request.QueryString["phase_id"]})" id="tableview" name="tableview" style="width:100%; min-height:600px; overflow-x:auto; border:none;"></iframe>*@

<div id="tabs" class="nav-tabs-custom" style="box-shadow: none; background: transparent;">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" class="tabMain" data-toggle="tab">Normal Parts</a></li>
        <li><a href="#tab2" class="tabMain" data-toggle="tab">Special Parts</a></li>
    </ul>

    <div class="tab-content" style="background: transparent;">
        <div id="tab1" class="active tab-pane">
            <div class="row">
                <div class="col-md-3 form-group">
                    <label>Ref. Model</label>
                    <label class="rsi-model"></label>
                </div>
            </div>
            <table id="normalTable" class="table table-bordered table-hover">
                <thead>
                    <tr class="bg-light-blue">
                        <th class="text-center" style="vertical-align:middle;"><i class="fa fa-minus-circle fa-changeall" aria-hidden="true"></i></th>
                        <th class="text-center" style="vertical-align:middle;">Partnumber_Top</th>
                        <th class="text-center" style="vertical-align:middle;">Partnumber_Parent</th>
                        <th class="text-center" style="vertical-align:middle;">Partnumber_Child</th>
                        <th class="text-center" style="vertical-align:middle;">Part No</th>
                        <th class="text-center" style="vertical-align:middle;">Partpath</th>
                        <th class="text-center" style="vertical-align:middle;">Level</th>
                        <th class="text-center" style="vertical-align:middle;">Material Group</th>
                        <th class="text-center" style="vertical-align:middle;">Material Parts</th>
                        <th class="text-center" style="vertical-align:middle;">Part Type</th>
                        <th class="text-center" style="vertical-align:middle;">English Name</th>
                        <th class="text-center" style="vertical-align:middle;">Part Level</th>
                        <th class="text-center" style="vertical-align:middle;">Part Description</th>
                        <th class="text-center" style="vertical-align:middle;">Vendor</th>
                        <th class="text-center" style="vertical-align:middle;">Maker PN</th>
                        <th class="text-center" style="vertical-align:middle;">Part Spec</th>
                        <th class="text-center" style="vertical-align:middle;">Spec Def</th>
                        <th class="text-center" style="vertical-align:middle;">Release Date</th>
                        <th class="text-center" style="vertical-align:middle;">Usage</th>
                        <th class="text-center" style="vertical-align:middle;">Unit</th>
                        <th class="text-center" style="vertical-align:middle;">Eol</th>
                        <th class="text-center" style="vertical-align:middle;">Uni Spec Stutas</th>
                        <th class="text-center" style="vertical-align:middle;">Remark</th>
                        <th class="text-center" style="vertical-align:middle;">Attach File</th>
                        <th class="text-center" style="vertical-align:middle;">Modify Type</th>
                        <th class="text-center" style="vertical-align:middle;">SN</th>
                    </tr>
                </thead>
            </table>
        </div>
        <div id="tab2" class="tab-pane">
            <div class="row">
                <div class="col-md-3 form-group">
                    <label>Ref. Model</label>
                    <label class="rsi-model"></label>
                </div>
            </div>

            <div id="specialTabs" class="nav-tabs-custom" style="background: transparent;">
                <ul class="nav nav-tabs"></ul>
                <div class="tab-content" id="specialContent" style="padding-left:0px; padding-right:0px; background: transparent;">
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12 text-center">
        <button class="btn bg-red btn-rejectmodal" data-toggle="modal" data-target="#rejectModal">Reject</button>
        <button class="btn bg-green btn-modal" data-toggle="modal" data-target="#myModal">Submit</button>
        @{
            var dt = RSI.Models.Entity.RSI_ConfigEntityDAL.GetExportExcelConfig(Model.BU, Model.PartType, Request.QueryString["phase_id"]);
            var exportexcel = dt.Rows.Count > 0 ? dt.Rows[0]["attribute5"] == null ? "hidden" : dt.Rows[0]["attribute5"].ToString() == "N" ? "hidden" : "" : "hidden";
        }
        <button class="btn bg-light-blue btn-exportExcel @exportexcel">Export</button>
    </div>
</div>

<form id="exportExcel" action="/RSI/RD/ExportExcel" method="post">
    <input type="hidden" name="rsi_no" id="rsi_no" />
    <input type="hidden" name="projectname" id="projectname" />
    <input type="hidden" name="bu" id="bu" />
    <input type="hidden" name="part_type" id="part_type" />
    <input type="hidden" name="phase_id" id="phase_id" />
    <input type="hidden" name="form_no" id="form_no" value="@Request.QueryString["form_no"].ToString()" />
    <input type="hidden" name="page_name" id="page_name" value="RDBossReivew" />
</form>

@Html.Action("DeatilApprove", "RSI", new { rsi_no = Request.QueryString["rsi_no"], part_type = Request.QueryString["part_type"], phase_id = Request.QueryString["phase_id"] })

@Html.Partial("~/Views/Process/Index.cshtml")

<div class="modal fade" id="fileManagement" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Download File</h4>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table class="table" id="fileTable" style="width:100%;">
                        <thead>
                            <tr class="bg-light-blue">
                                <th class="text-center">File Name</th>
                                <th class="text-center">File Size(KB)</th>
                                <th class="text-center">Upload by</th>
                                <th class="text-center">Upload Date</th>
                                <th class="text-center">Remark</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@{
    string version = RSI.Models.Entity.RSI_ConfigEntityDAL.GetVersion();
}

@section custom_script_reference{
    @Html.Partial("~/Views/RSI/LoadingPage.cshtml")
    <script src="@Url.Content("~/Content/Scripts/jquery.dataTables.min.js?" + version)"></script>
    <script src="@Url.Content("~/Content/Scripts/dataTables.bootstrap.min.js?" + version)"></script>
    <script src="@Url.Content("~/Content/Third-Part/Select-1.2.6/js/dataTables.select.min.js?" + version)"></script>
    <script src="@Url.Content("~/Content/Third-Part/Select-1.2.6/js/select.bootstrap.min.js?" + version)"></script>
    <script src="@Url.Content("~/Scripts/RDBossReview.js?" + version)"></script>
}