RSI/Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RSI.Models.Manager;
using RSI.Models.Entity;
using System.Web.Security;
using AUO.Common.Authentication;

namespace RSI.Controllers
{
    public class DemoController : Controller
    {
        /// <summary>
        /// 展示view示例
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            RSI_ConfigEntityDAL.LoginLog(Employee.EmpNO);
            var model = To_Do_List_VManager.GetTo_Do_List_VEntities(Employee.EmpNO);
            return View(model);
        }

        public ActionResult Form()
        {
            return View();
        }

        [OutputCache(CacheProfile = "CacheProfile")]
        public ActionResult Table(string id = "13")
        {
            //做Oracle DB访问捞取数据的demo演示
            var list = WIPManager.GetWIPInfo(id);
            return View(list);
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Error()
        {
            return View();
        }

        public ActionResult Element()
        {
            return View();
        }

        public ActionResult Notice()
        {
            return View();
        }

        public ActionResult OracleTest()
        {
            var list = BPS_Item_ConfigManager.GetBPS_Item_Configs();
            return View(list);
        }


        #region Sample页面
        // GET: Repair
        /// <summary>
        /// 提供调用webapi示例程式，及与view做简单数据传输的示例
        /// </summary>
        /// <returns></returns>
        //public ActionResult SampleView(string id)
        //{
        //try
        //{
        //    //FormsAuthTicketData ticketData = new FormsAuthTicketData((HttpContext.User.Identity as FormsIdentity).Ticket);   //获取CAP中的用户身份信息
        //    //string tempJsonDorm = WebApiHelper.GetMethod("Repair/GetDormList?site=" + ticketData.Site + "&dorm_id=");

        //    string tempJsonDorm = WebApiHelper.GetMethod("Samples/GetDormList?site=" + "AUSZ" + "&dorm_id=");
        //    DataTable dtDorm = JsonConvert.DeserializeObject<DataTable>(tempJsonDorm);
        //    ViewBag.dtDorm = dtDorm;
        //    ViewBag.dormitory_manage_info = dtDorm.Rows.Count > 0 ? string.IsNullOrEmpty(dtDorm.Rows[0]["supervisor_contact_number"].ToString()) ? "" : dtDorm.Rows[0]["supervisor_contact_number"].ToString() : "";
        //    ViewBag.hr_info = dtDorm.Rows.Count > 0 ? string.IsNullOrEmpty(dtDorm.Rows[0]["hr_supervisor_empno"].ToString()) ? "" : dtDorm.Rows[0]["hr_supervisor_empno"].ToString() : "";
        //    return View();
        //}
        //catch (Exception ex)
        //{
        //    LogHelper.GetLogger("DemoView ").Error(ex.ToString());
        //    return View("Error");
        //}
        //}
        #endregion

        [HttpPost]
        public ActionResult ToDoListUpdateTag(string rsi_no, string form_no, string phase_id, string app_serial, string app_status, string tag)
        {
            rsi_no = Validate.DecryptValue(rsi_no);
            form_no = Validate.DecryptValue(form_no);
            return Json(To_Do_List_VManager.ToDoListUpdateTag(rsi_no, form_no, phase_id, app_serial, app_status, tag));
        }

        [HttpPost]
        public ActionResult ToDoListUpdateRemark(string rsi_no, string form_no, string phase_id, string app_serial, string app_status, string remark)
        {
            rsi_no = Validate.DecryptValue(rsi_no);
            form_no = Validate.DecryptValue(form_no);
            return Json(To_Do_List_VManager.ToDoListUpdateRemark(rsi_no, form_no, phase_id, app_serial, app_status, remark));
        }
    }
}

RSI/Controllers/RSIController.cs
using AUO.Common.Authentication;
using RSI.Models.Entity;
using RSI.Models.Manager;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace RSI.Controllers
{
    public class RSIController : Controller
    {
        // GET: RSI
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult BasicPage()
        {
            var rsi_no = Validate.DecryptValue(Request.QueryString["rsi_no"]);
            var part_type = Validate.DecryptValue(Request.QueryString["part_type"]);
            H_Product_InfoEntity h_Product_Info = H_Product_InfoManager.GetH_Product_InfoEntities(rsi_no, part_type).FirstOrDefault();
            return View(h_Product_Info);
        }

        public ActionResult DashBoard()
        {
            DashBoardVM model = new DashBoardVM();

            var project_name = Request.QueryString["project_name"];
            var rfq_no = Request.QueryString["rfq_no"];
            var rfq_ver = Request.QueryString["rfq_ver"];
            if (project_name != null || rfq_no != null || rfq_ver != null) {
                project_name = project_name != null ? project_name.ToString() : string.Empty;
                rfq_no = rfq_no != null ? rfq_no.ToString() : string.Empty;
                rfq_ver = rfq_ver != null ? rfq_ver.ToString() : string.Empty;
                var rsi_no = DASHBOARD_LIST_VManager.GetDashBoardRSINO(project_name, rfq_no, rfq_ver);
                rsi_no = String.IsNullOrEmpty(rsi_no) ? " " : rsi_no;
                string owner = "2";
                string contractStatus = "ALL";
                ViewData["Owner"] = owner;
                ViewData["contractStatus"] = contractStatus;
                ViewData["projectName"] = rsi_no;
                model.UA = DASHBOARD_LIST_VManager.GetDashBoardUA(owner, contractStatus, rsi_no);
            }
            else
            {
                string owner = "1";
                string contractStatus = "UA";
                project_name = String.Empty;
                model.UA = DASHBOARD_LIST_VManager.GetDashBoardUA(owner, contractStatus, project_name);

            }
            return View(model);
        }

        [HttpPost]
        public ActionResult DashBoard(string owner,string contractStatus, string project_name)
        {
            DashBoardVM model = new DashBoardVM();
            model.UA = DASHBOARD_LIST_VManager.GetDashBoardUA(owner, contractStatus, project_name);
            ViewData["Owner"] = owner;
            ViewData["contractStatus"] = contractStatus;
            ViewData["projectName"] = project_name;


            return View(model);
        }

        [HttpPost]
        public ActionResult DashBoard_DeatilApprove(string rsi_no, string part_type)
        {
            var result = DASHBOARD_LIST_VManager.GetDetailApprove(rsi_no, part_type);
            return Json(result);
        }

        public ActionResult DetailLayer1(string rsi_no, string phase_id, string form_status, string part_type)
        {
            var model = DASHBOARD_LAYER1_VManager.GetDashBoardLayer1(rsi_no, phase_id, form_status, part_type);
            return View(model);
        }

        public ActionResult DetailLayer1SourcerView(string rsi_no, string phase_id, string form_status, string part_type)
        {
            var model = DASHBOARD_LAYER1_VManager.GetDashBoardLater1Sourcer(rsi_no, phase_id, form_status, part_type);
            return View(model);
        }

        public ActionResult DetailLayer2(string rsi_no, string app_status, string form_status, string part_type)
        {
            var model = DASHBOARD_LAYER2_VManager.GetDashBoardLayer2(rsi_no, app_status, form_status, part_type);
            return View(model);
        }

        public ActionResult Layer1Return()
        {
            var rsi_no = Validate.DecryptValue(Request.QueryString["rsi_no"]);
            var part_type = Validate.DecryptValue(Request.QueryString["part_type"]);
            H_Product_InfoEntity h_Product_Info = H_Product_InfoManager.GetH_Product_InfoEntities(rsi_no, part_type).FirstOrDefault();
            return View(h_Product_Info);
        }

        public ActionResult Layer1_RDReview()
        {
            var rsi_no = Validate.DecryptValue(Request.QueryString["rsi_no"]);
            var part_type = Validate.DecryptValue(Request.QueryString["part_type"]);
            H_Product_InfoEntity h_Product_Info = H_Product_InfoManager.GetH_Product_InfoEntities(rsi_no, part_type).FirstOrDefault();
            return View(h_Product_Info);
        }

        public ActionResult Layer1View_Sourcer()
        {
            var rsi_no = Validate.DecryptValue(Request.QueryString["rsi_no"]);
            var part_type = Validate.DecryptValue(Request.QueryString["part_type"]);
            H_Product_InfoEntity h_Product_Info = H_Product_InfoManager.GetH_Product_InfoEntities(rsi_no, part_type).FirstOrDefault();
            return View(h_Product_Info);
        }

        public ActionResult Layer1View_SourcerDocument()
        {
            var rsi_no = Validate.DecryptValue(Request.QueryString["rsi_no"]);
            var part_type = Validate.DecryptValue(Request.QueryString["part_type"]);
            H_Product_InfoEntity h_Product_Info = H_Product_InfoManager.GetH_Product_InfoEntities(rsi_no, part_type).FirstOrDefault();
            return View(h_Product_Info);
        }

        public ActionResult Layer1View_PMConfirm()
        {
            var rsi_no = Request.QueryString["rsi_no"];
            rsi_no = Validate.DecryptValue(rsi_no);
            var groups_id = H_Product_DetailManager.GetGroupID(rsi_no);
            var model = new List<C_MTL_PARTSEntity>();
            if (groups_id.Count() == 0)
            {
                var group_result = C_MTL_PARTSManager.GetC_MTL_PARTSEntities(rsi_no, "");
                group_result = group_result.Select(p => new C_MTL_PARTSEntity()
                {
                    RSI_NO = rsi_no,
                    GROUP_ID = "",
                    GROUP_DESC = "",
                    PART_TYPE = p.PART_TYPE,
                    MTL_GROUP = p.MTL_GROUP,
                    MTL_GROUP_TOTAL = p.MTL_GROUP_TOTAL
                }).ToList();
                model.AddRange(group_result);
            }
            else
            {
                foreach (var group_id in groups_id)
                {
                    var group_result = C_MTL_PARTSManager.GetC_MTL_PARTSEntities(rsi_no, group_id);
                    group_result = group_result.Select(p => new C_MTL_PARTSEntity()
                    {
                        RSI_NO = rsi_no,
                        GROUP_ID = group_id,
                        PART_TYPE = p.PART_TYPE,
                        MTL_GROUP = p.MTL_GROUP,
                        MTL_GROUP_TOTAL = p.MTL_GROUP_TOTAL
                    }).ToList();
                    model.AddRange(group_result);
                }
            }


            return View(model);
        }

        public ActionResult GetToDoListCount()
        {
            var model = To_Do_List_VManager.GetTo_Do_List_VEntities(Employee.EmpNO);
            return Content(model.Count().ToString());
        }

        public ActionResult GetEmp_EngName()
        {
            FormsAuthenticationTicket ticket = (HttpContext.User.Identity as FormsIdentity).Ticket;
            var eng_name = ticket.Name.Split('\\')[1].ToString();
            return Content(eng_name);
        }

        public ActionResult GetDepartmentId()
        {
            FormsAuthenticationTicket ticket = (HttpContext.User.Identity as FormsIdentity).Ticket;
            FormsAuthTicketData ticketData = new FormsAuthTicketData(ticket);
            var result = string.Format("{0} {1}", ticketData.DepartmentId, Employee.GetDepartmentName(Employee.EmpNO));
            return Content(result);
        }

        public ActionResult GetFile(string file_id, string rsi_no, string sn)
        {
            string biz_id = String.Format("{0}_{1}", rsi_no, sn);
            if (string.IsNullOrEmpty(sn))
                biz_id = rsi_no;
            var filelist = FileManagementManager.GetFilelist(biz_id);

            var file_name = filelist.Where(p => p.FILE_ID == file_id).Select(p => p.FILE_NAME).FirstOrDefault();
            var emp_no = filelist.Where(p => p.FILE_ID == file_id).Select(p => p.CREATED_BY).FirstOrDefault();

            byte[] fileStream = null;

            using (FLM.FLMServiceClient client = new FLM.FLMServiceClient())
            {
                client.ClientCredentials.UserName.UserName = ConfigurationManager.AppSettings["FLMUser"];
                //WCF用戶名，新系統申請時分配(測試區固定：flm_public)
                client.ClientCredentials.UserName.Password = ConfigurationManager.AppSettings["FLMPWD"];
                //WCF密碼，新系統申請時分配(測試區固定：p@ssw0rd)
                string fileID = file_id;
                string fileName = file_name;
                string empNo = emp_no;
                bool getPdf = false;
                //PDF文件設定
                fileStream = client.GetFile(fileID, ref fileName, empNo, getPdf, null);
            }

            return File(fileStream, "application/unknown", file_name);
        }

        public ActionResult SearchEmp() {
            return View();
        }

        public ActionResult NoMacAddress()
        {
            return View();
        }

        public ActionResult Tips()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SearchEmp(string search, string phase_id, string part_type, string bu)
        {
            //var employees = new List<EmployeeModel>();
            //if (!String.IsNullOrEmpty(search)) {
            //    employees = Employee.GetEmpoyee(search, phase_id, part_type, bu).ToList();
            //}
            
            //return Json(employees);

RSI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title</title>

    @*  Sample demo to reference JS&Css with Bundles*@
    @Styles.Render("~/bundles/style")
    @Styles.RenderFormat("<link href='{0}' rel='stylsheet' type='text/css' media='print' />", "~/bundles/style/print")
    @RenderSection("custom_css_reference", required: false)
    @RenderSection("custom_style", required: false)
    <style type="text/css">
        body {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        iframe body {
            -webkit-touch-callout: initial;
            -webkit-user-select: text;
            -moz-user-select: text;
            -ms-user-select: text;
            user-select: text;
        }

        .main-header .logo {
            width: 180px;
        }
        .main-header .navbar {
            margin-left:180px;
        }
    </style>
</head>
<body class="sidebar-mini skin-blue-light fixed" oncontextmenu="return false">
    <!-- fixed ie8不適用 -->

    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index", "Demo")" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><img src="@Url.Content("~/Content/images/logo.png")"></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><img src="@Url.Content("~/Content/images/logo.png")"> <b>RSI</b></span>
            </a>
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- Notifications Menu -->
                        <li class="dropdown notifications-menu">
                            <!-- Menu toggle button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-bell-o"></i>
                                <span class="label label-danger">@Html.Action("GetToDoListCount", "RSI")</span>
                            </a>
                            @{
                                var todolist = RSI.Models.Manager.To_Do_List_VManager.GetTo_Do_List_VEntities(RSI.Models.Entity.Employee.EmpNO);
                            }
                            <ul class="dropdown-menu">
                                <li class="header">To do list</li>
                                <li>
                                    <ul class="menu">
                                        @foreach (var item in todolist)
                                        {
                                            var url = "/RSI";
                                            switch (item.PHASE_ID)
                                            {
                                                case "10":
                                                    url += "/RD/RDReview";
                                                    break;
                                                case "20":
                                                    url += "/RD/RDBossReview";
                                                    break;
                                                case "25":
                                                    url += "/RD/RDBossReview";
                                                    break;
                                                case "30":
                                                    url += "/PM/PLReview";
                                                    break;
                                                case "40":
                                                    url += "/Sourcer/Index";
                                                    break;
                                                case "45":
                                                    url += "/Sourcer/ProductReview";
                                                    break;
                                                case "50":
                                                    url += "/Sourcer/Boss";
                                                    break;
                                                case "60":
                                                    url += "/Sourcer/Boss";
                                                    break;
                                                case "70":
                                                    url += "/PM/Confirm";
                                                    break;
                                            }
                                            url += "?rsi_no={0}&part_type={1}&form_no={2}&phase_id={3}";
                                            url = string.Format(url, RSI.Models.Entity.Validate.EncryptValue(item.RSI_NO.ToString()), RSI.Models.Entity.Validate.EncryptValue(item.PART_TYPE), RSI.Models.Entity.Validate.EncryptValue(item.FORM_NO.ToString()), item.PHASE_ID);
                                            <li>
                                                <a href="@url">
                                                    <i class="fa fa-chevron-right text-aqua"></i> @item.PROJECT_NAME&nbsp;@item.PART_TYPE
                                                </a>
                                            </li>
                                        }
                                    </ul>
                                </li>
                                <li class="footer"><a href="#">更多</a></li>
                            </ul>
                        </li>
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                @{
                                    var emp_no = RSI.Models.Entity.Employee.EmpNO;
                                    var imageUrl = String.Format("http://au3hr8/photo/{0}.jpg", emp_no);
                                }
                                <div class="user-image"><img src="@imageUrl" alt="User Image"></div>
                                <span class="hidden-xs">@RSI.Models.Entity.Employee.EmpName</span>
                            </a>
                            <ul class="dropdown-menu notifications-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <div class="img-circle"><img src="@imageUrl" alt="User Image"></div>
                                    <p>
                                        @Html.Action("GetEmp_EngName", "RSI")&nbsp;@RSI.Models.Entity.Employee.EmpName
                                        <small>@Html.Action("GetDepartmentId", "RSI")</small>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Personal Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        @Html.ActionLink("Logout", "SingOut", "RSI", null, new { @class = "btn btn-default btn-flat" })
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <!-- Language Menu -->
                        <li class="dropdown notifications-menu language-menu">
                            <!-- Menu toggle button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-globe"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <ul class="menu">
                                        <li><a href="#">English</a></li>
                                        <li><a href="#">繁體中文</a></li>
                                        <li><a href="#">简体中文</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar" style="width:180px;">
            <section class="sidebar">
                <!-- Sidebar Menu -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="active"><a href="@Url.Action("Index", "Demo")"><i class="fa fa-home"></i> <span>Home</span></a></li>
                    <li>
                        <a href="@Url.Action("DashBoard", "RSI")">
                            <i class="fa fa-file-text"></i> <span>DashBoard</span>
                        </a>
                    </li>
                </ul>
                <!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper" style="margin-left:180px;">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>@ViewBag.SubTitle</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="@Url.Action("Index", "Demo")"><i class="fa fa-home"></i> Home</a></li>
                    <li class="active">@ViewBag.Title</li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content container-fluid">
                @RenderBody()
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            @RenderSection("warning", false)
            <!-- To the right -->
            <div class="pull-right hidden-xs">
                Owner: Yihui 李怡慧(8535-5550)
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2018 <a href="/RSI">RSI</a>.</strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
    @Scripts.Render("~/bundles/script")
    @RenderSection("custom_script_reference", required: false)
    @RenderSection("custom_script", false)
    <script>
        $(function () {
            $('.content-wrapper').css({ "background-image": "url(http://auhqhrap02.corpnet.auo.com/PB20/Webform/GetSpecialWaterMark.ashx)", "background-repeat": "repeat", "background-position": "center" });
        });
    </script>
</body>
</html>